### ISSUE TITLE
Model Tracking: Junker Light Fighter

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#159]
The Junker light fighter, currently in as the 'Manta'. Listed in #157.

### Model Checklist

- [x] Base .3db/cmp components
- [x] Textures
- [x] .mat file
- [x] Wireframed
- [x] Hardpointed
- [x] Hardpoint stubs
- [x] Hitboxed (Hull)
- [x] Hitboxed (Shield)
- [x] Hitboxes tested ingame
- [x] Cargobay animations
- [x] Damage models (If applicable)
- [x] XML uploaded

### INI Checklist

- [x] INI definitions
- [x] Placeholder infocards for ship written to infocard_imports.frc
- [x] Placeholder infocards for innate equipment written to infocard_imports.frc (Engines, Scanners, etc)

### Extras

- [x] VFX (If applicable)
- [ ] SFX (if applicable)

**Comment by IrateRedKite** [comment]
Currently a few bugs with this one: There's a handful of missing textures that aren't defined in the .mat and need to be referenced in the INI. The wireframe display ingame seems inconsistent and doesn't always show up, and there appear to be a number of odd hitbox issues for shield and hull that need to be resolved.

**Comment by IrateRedKite** [comment]
Closed with f23782d7b9db175e3845bf2a80b2c72ec5ef74b3
