### ISSUE TITLE
Model Tracking: Junker Heavy Fighter

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#160]
Currently in as the Angler, listed in #157 

### Model Checklist

- [x] Base .3db/cmp components
- [x] Textures
- [x] .mat file
- [x] Wireframed
- [x] Hardpointed
- [x] Hardpoint stubs
- [x] Hitboxed (Hull)
- [x] Hitboxed (Shield)
- [x] Hitboxes tested ingame
- [x] Cargobay animations
- [x] Damage models
- [x] XML uploaded

### INI Checklist

- [x] INI definitions
- [x] Placeholder infocards for ship written to infocard_imports.frc
- [x] Placeholder infocards for innate equipment written to infocard_imports.frc (Engines, Scanners, etc)

### Extras

- [x] VFX
- [ ] SFX

**Comment by IrateRedKite** [comment]
Minor nitpick that should probably be fixed for this model: The cockpit mesh clips outside the model ever-so-slightly as highlighted below:

![Image](https://github.com/better-modernized-combat/bmod-client/assets/12358715/75d578dc-d71c-4add-b17d-99965caa26c6)
