### ISSUE TITLE
Model Tracking: Junker Very Heavy Fighter

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#161]
Currently in as the Orca, listed in #157 

### Model Checklist

- [x] Base .3db/cmp components
- [x] Textures
- [x] .mat file
- [x] Wireframed
- [x] Hardpointed
- [x] Hardpoint stubs
- [x] Hitboxed (Hull)
- [x] Hitboxed (Shield)
- [x] Hitboxes tested ingame
- [x] Cargobay animations
- [x] Damage models
- [x] XML uploaded

### INI Checklist

- [x] INI definitions
- [x] Placeholder infocards for ship written to infocard_imports.frc
- [x] Placeholder infocards for innate equipment written to infocard_imports.frc (Engines, Scanners, etc)

### Extras

- [x] VFX
- [ ] SFX
