### ISSUE TITLE
Model Tracking: Independence

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#162]
The independence Xenos frigate, currently listed in #157

### Model Checklist

- [ ] Base .3db/cmp components
- [ ] Textures
- [ ] .mat file
- [ ] Wireframed
- [ ] Hardpointed
- [ ] Hardpoint stubs
- [ ] Hitboxed (Hull)
- [ ] Hitboxed (Shield)
- [ ] Hitboxes tested ingame
- [ ] Damage models (If applicable)
- [ ] XML uploaded

### INI Checklist

- [ ] INI definitions
- [ ] Placeholder infocards for ship written to infocard_imports.frc
- [ ] Placeholder infocards for innate equipment written to infocard_imports.frc (Engines, Scanners, etc)

### Extras

- [ ] VFX
- [ ] SFX
