### ISSUE TITLE
Model Tracking: The Ludlow

### ISSUE THREAD

**Issue by IrateRedKite** [better-modernized-combat/bmod-client#163]
The Ludlow Xenos converted mining ship, mentioned in  #157

### Model Checklist

- [ ] Base .3db/cmp components
- [ ] Textures
- [ ] .mat file
- [ ] Wireframed
- [ ] Hardpointed
- [ ] Hardpoint stubs
- [ ] Hitboxed (Hull)
- [ ] Hitboxed (Shield)
- [ ] Hitboxes tested ingame
- [ ] Damage models
- [ ] XML uploaded

### INI Checklist

- [ ] INI definitions
- [ ] Placeholder infocards for ship written to infocard_imports.frc
- [ ] Placeholder infocards for innate equipment written to infocard_imports.frc (Engines, Scanners, etc)

### Extras

- [ ] VFX
- [ ] SFX
